### ISSUE TITLE
add "shell readability" serie

### ISSUE THREAD

**Issue by Sarcasm** [jmmv/jmmv.github.io#3]
Hello,

I read your articles about shell readability and I found them interesting!
I was wondering if you were willing to group them in a serie, like you did for "CLI design", so that I can refer people to this page eventually?

Thanks!

**Comment by jmmv** [comment]
Hey,

Apologies for the long delay. I wanted to refactor a few things in the blog before addressing your suggestion in order to better handle formal series (like the older ones, which had an introduction and a wrap-up) and the more ad-hoc ones like this which were never planned in the first place.  Travel got in the way also... but finally got to this!

Hopefully this works! http://julio.meroh.net/essays.html#series-Shell%20readability

**Comment by Sarcasm** [comment]
Thank you!

A few remarks:
- for featured articles, I understand the ordering from most recent to oldest, but for series, I find it weird that it starts with a wrap-up post, and ends up with an introduction.
- how to get the hyperlink you provided with the HTML fragment without looking at the HTML source?
- on both of my browsers (Chrome, Firefox), the URL (with fragment) does not show the page at the start of the section, see screenshot below

What I get:

![image](https://user-images.githubusercontent.com/424046/39993458-34d0c212-5776-11e8-8e53-e629e7564270.png)

What I expected (had to scroll manually):
![image](https://user-images.githubusercontent.com/424046/39993547-825da5b8-5776-11e8-8008-5439def2a55e.png)

**Comment by jmmv** [comment]
Thanks for your feedback!

The bad anchoring was known to me but I had been lazy in fixing it because it was hard to find a solution to.

I've addressed your suggestions now. They are some corner cases that don't show up great, but I think they more or less work. However, at this point I'm not too happy about "Series" and "Archive" being subsections of the "Essays" page; I might turn those into top-level pages.

Let me know!

**Comment by jmmv** [comment]
Just to close on this: I've gone ahead and created a separate "series" page. The link to the Shell readability series is thus: http://julio.meroh.net/series.html#series-Shell%20readability , which I think makes more sense than the previous one. Apologies for the change!
